import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()  # Load environment variables from .env file

DATABASE_URL = os.getenv("DATABASE_URL")

print("connecting to database...")
try:
    engine = create_engine(DATABASE_URL, echo=True)

    # echo=True is used to log all the SQL statements generated by SQLAlchemy to the console. This is useful for debugging and understanding how SQLAlchemy interacts with the database.
    with engine.connect() as connection:
        result = connection.execute(text("SELECT version();"))
        version = result.fetchone()[0]
        print(f"Connected to database. PostgreSQL version: {version}")

except Exception as e:
    print(f"Error connecting to database: {e}")